name: deployment
on:
  workflow_dispatch:
 # push:
   # branches:
    #- main
    
env:
  
  aws-region: us-east-1

jobs:
  terraform_plan:
    name: terraform
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup terraform hashicorp
        uses: hashicorp/setup-terraform@v2 
        with:
          terraform_version: 1.1.7

        
      
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1   
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          Aws-region: ${{env.aws-region}}

      
      - name: terraform init  
        run: |
          cd mainfiles
          terraform init -reconfigure 
      
      - name: terraform plan
        run: |
          cd mainfiles
          terraform plan -var-file="terraform.tfvars"
      - name: terraform apply
      
        run: |
          cd mainfiles
          terraform apply -var-file="terraform.tfvars" -auto-approve 
